"""Standalone async event bus for the Proactive Agent.

Provides typed pub/sub event dispatching with per-handler task isolation.
Inspired by the Safari agent framework's EventBus pattern but fully
standalone with zero external dependencies.

Architecture
------------
The EventBus wraps a single ``asyncio.Queue`` with typed pub/sub semantics:

    publish(event) → Queue → _event_queue_loop → _dispatch_event → fan-out

Each registered handler receives its own ``asyncio.Task``, so handlers run
concurrently without blocking each other or the dispatch loop.

Performance
-----------
A single EventBus instance is used for the entire agent. This is efficient
because:

* The internal queue is an unbounded ``asyncio.Queue`` — no contention.
* Dispatch is O(handlers-per-event-type), typically < 5.
* Each handler runs in its own task — no blocking between handlers.
* Hot-path data (audio/video frames) still flows directly via
  ``stream.Send()`` in Observation; the bus carries only metadata events
  (REAL_TIME_IMAGE_SENT, TEXT_INPUT) for logging and UI updates.

Multiple bus instances are NOT needed. The overhead of a single bus dispatch
(enqueue + dict lookup + create_task) is negligible compared to network I/O.

Event Sources
-------------
Events are categorized by two sources:

* **ASSISTANT** — Events produced by the AI model, agent logic, and system
  infrastructure (model responses, tool call requests, audio/text output,
  system logs, errors).
* **USER** — Events originating from the external world: human input,
  robot/embodiment actions, sensor data, and tool execution results.

Event Types
-----------
Event types are organized by source category. See ``EventType`` enum for
the full list with descriptions.
"""

import asyncio
import collections
import collections.abc
import dataclasses
import datetime
import enum
import logging
from typing import Any, Callable

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Event Source
# ---------------------------------------------------------------------------


@enum.unique
class EventSource(enum.Enum):
  """Identifies which side of the agent boundary produced an event.

  There are exactly two categories:

  * ASSISTANT — The AI model and its supporting infrastructure. This includes
    Gemini model responses, tool call requests initiated by the model, text
    and audio output generated by the model, system log messages, and
    internal errors.

  * USER — The external world. This includes human text/audio input, camera
    frames from the robot or webcam, tool execution results returned by the
    embodiment/robot, and any other data originating outside the model.
  """

  ASSISTANT = "ASSISTANT"
  USER = "USER"


# ---------------------------------------------------------------------------
# Event Types (organized by source)
# ---------------------------------------------------------------------------


@enum.unique
class EventType(enum.Enum):
  """All event types in the Proactive Agent.

  Organized by the source that typically produces them.
  """

  # === ASSISTANT events (from the AI model / agent system) ================

  # Raw response from the Gemini BidiGenerateContent stream.
  MODEL_RESPONSE = "MODEL_RESPONSE"

  # Model requests one or more tool calls. Payload: tool_call proto.
  TOOL_CALL = "TOOL_CALL"

  # Model generated text output. Payload: {"text": str}.
  GEMINI_TEXT = "GEMINI_TEXT"

  # Model generated thinking process (internal monologue). Payload: {"text": str}.
  GEMINI_THOUGHT = "GEMINI_THOUGHT"

  # Raw audio chunk from model turn (pre-WAV encoding).
  # Payload: bytes (PCM audio data).
  AUDIO_CHUNK = "AUDIO_CHUNK"

  # Encoded audio response (WAV, base64). Published by AudioResponseHandler
  # after accumulating AUDIO_CHUNKs. Payload: {"audio_data": str}.
  AUDIO_RESPONSE = "AUDIO_RESPONSE"

  # Model finished its current turn.
  TURN_COMPLETE = "TURN_COMPLETE"

  # Performance and token usage metrics.
  TELEMETRY = "TELEMETRY"

  # Model turn was interrupted by new user input.
  INTERRUPTED = "INTERRUPTED"

  # Session has terminated (stream closed or error).
  SESSION_DONE = "SESSION_DONE"

  # Transparent history update from the model. Payload: TransparentHistoryUpdate proto.
  TRANSPARENT_HISTORY = "TRANSPARENT_HISTORY"

  # System log message. Payload: dict with level, message, module, etc.
  LOG = "LOG"

  # System or environment error. Payload: str (error description).
  ERROR = "ERROR"

  # === USER events (from human / robot / environment) =====================

  # User typed text input. Payload: str.
  TEXT_INPUT = "TEXT_INPUT"

  # Transcription of user's audio input. Payload: {"text": str}.
  USER_TRANSCRIPT = "USER_TRANSCRIPT"

  # Camera frame sent to the model. Payload: bytes (JPEG).
  REAL_TIME_IMAGE_SENT = "REAL_TIME_IMAGE_SENT"

  # Tool execution result from the robot/embodiment.
  # Payload: dict with name, args, result, action_data.
  TOOL_RESULT = "TOOL_RESULT"

  # Request to send a heartbeat (flush buffers with fresh visual context).
  HEARTBEAT_TRIGGER = "HEARTBEAT_TRIGGER"


# ---------------------------------------------------------------------------
# Event
# ---------------------------------------------------------------------------


@dataclasses.dataclass(frozen=True)
class Event:
  """Immutable event with auto-timestamping.

  Attributes:
    type: The event type (determines which handlers receive it).
    source: Whether the event came from the ASSISTANT or USER side.
    data: Arbitrary payload (proto, dict, bytes, str, etc.).
    metadata: Optional key-value metadata for downstream handlers.
    timestamp: UTC timestamp, auto-set on creation.
  """

  type: EventType
  source: EventSource
  data: Any = None
  metadata: dict[str, Any] = dataclasses.field(default_factory=dict)
  timestamp: datetime.datetime = dataclasses.field(
      default_factory=lambda: datetime.datetime.now(datetime.timezone.utc)
  )


# Handler signature: async or sync callable taking an Event.
EventHandler = Callable[[Event], Any]


# ---------------------------------------------------------------------------
# EventBus
# ---------------------------------------------------------------------------


class EventBus:
  """Async event bus with typed pub/sub and per-handler task isolation.

  Usage::

      bus = EventBus()
      bus.subscribe([EventType.TOOL_CALL], my_handler)
      bus.start()
      await bus.publish(Event(type=EventType.TOOL_CALL, ...))
      ...
      await bus.shutdown()

  Thread safety:
      ``publish_nowait()`` is safe to call from non-async callbacks (e.g.,
      gRPC threads) via ``loop.call_soon_threadsafe(bus.publish_nowait,
      event)``.
  """

  def __init__(self):
    self._handlers_by_event_type: dict[EventType, set[EventHandler]] = (
        collections.defaultdict(set)
    )
    self._event_queue: asyncio.Queue[Event] = asyncio.Queue()
    self._main_task: asyncio.Task[None] | None = None
    self._handler_tasks: dict[str, asyncio.Task[None]] = {}
    self._is_running = False

  @property
  def is_running(self) -> bool:
    return self._is_running

  def subscribe(
      self,
      event_types: collections.abc.Sequence[EventType],
      handler: EventHandler,
  ) -> None:
    """Registers a handler for one or more event types.

    Multiple handlers can subscribe to the same event type.
    A single handler can subscribe to multiple event types.

    Args:
      event_types: Event types to subscribe to.
      handler: Async or sync callable taking an Event.
    """
    for event_type in event_types:
      self._handlers_by_event_type[event_type].add(handler)

  def unsubscribe(self, handler: EventHandler) -> None:
    """Removes a handler from all event types."""
    for handlers in self._handlers_by_event_type.values():
      handlers.discard(handler)

  def unsubscribe_all(self) -> None:
    """Removes all handlers."""
    self._handlers_by_event_type.clear()

  async def publish(self, event: Event) -> None:
    """Publishes an event to the bus.

    The event is enqueued and dispatched asynchronously to all registered
    handlers. This method returns immediately after enqueuing.

    Args:
      event: The event to publish.
    """
    await self._event_queue.put(event)

  def publish_nowait(self, event: Event) -> None:
    """Publishes an event without awaiting. For use from sync callbacks.

    Typically called via::

        loop.call_soon_threadsafe(bus.publish_nowait, event)

    Args:
      event: The event to publish.
    """
    self._event_queue.put_nowait(event)

  def start(self) -> None:
    """Starts the event dispatch loop as a background task."""
    if self._main_task and not self._main_task.done():
      logger.info("EventBus: dispatch loop already running.")
      return
    self._main_task = asyncio.create_task(self._event_queue_loop())
    self._is_running = True
    logger.info("EventBus: started.")

  async def shutdown(self) -> None:
    """Shuts down the bus: cancels dispatch loop and all pending handler tasks."""
    if not self._main_task or self._main_task.done():
      logger.info("EventBus: already stopped.")
      return

    logger.info("EventBus: shutting down...")
    self._main_task.cancel()
    try:
      await asyncio.wait_for(self._main_task, timeout=2.0)
    except (asyncio.CancelledError, asyncio.TimeoutError):
      pass
    self._main_task = None
    self._is_running = False

    # Cancel all pending handler tasks with a timeout.
    tasks_to_cancel = [t for t in self._handler_tasks.values() if not t.done()]
    if tasks_to_cancel:
      logger.info(
          "EventBus: cancelling %d pending handler tasks...",
          len(tasks_to_cancel),
      )
      for task in tasks_to_cancel:
        task.cancel()
      _, pending = await asyncio.wait(tasks_to_cancel, timeout=5.0)
      if pending:
        logger.warning(
            "EventBus: %d handler tasks did not finish within 5s timeout.",
            len(pending),
        )
    self._handler_tasks.clear()
    logger.info("EventBus: shutdown complete.")

  async def _event_queue_loop(self) -> None:
    """Main dispatch loop: dequeues events and fans out to handlers."""
    while True:
      try:
        event = await self._event_queue.get()
        await self._dispatch_event(event)
      except asyncio.CancelledError:
        break

  def _on_handler_done(self, task: asyncio.Task[None]) -> None:
    """Logs exceptions when a handler task completes."""
    self._handler_tasks.pop(task.get_name(), None)
    if not task.cancelled():
      exc = task.exception()
      if exc:
        logger.exception("EventBus handler failed: %s", exc)

  async def _dispatch_event(self, event: Event) -> None:
    """Dispatches an event to all registered handlers for its type."""
    handlers = self._handlers_by_event_type.get(event.type)
    if not handlers:
      return

    for handler in handlers:
      if asyncio.iscoroutinefunction(handler):
        task = asyncio.create_task(handler(event))
      else:
        # Sync handlers run in a thread to avoid blocking the loop.
        task = asyncio.create_task(asyncio.to_thread(handler, event))

      # Track the task and auto-remove on completion.
      task_name = task.get_name()
      self._handler_tasks[task_name] = task
      task.add_done_callback(self._on_handler_done)
